### ISSUE TITLE
Is it possible to get/use MIDI input?

### ISSUE THREAD

**Issue by E3V3A** [pimoroni/Piano-HAT#14]
Great Project! 

Can you also use MIDI as input on this piano? 
How to do it?

**Comment by Gadgetoid** [comment]
MIDI input from another keyboard to trigger the piano samples included with this piano?

You'd probably need to build something with Mido, or a similar library: https://mido.readthedocs.io/en/latest/

That said, reading the midi data from a raw port isn't complex, the protocol is quite simple.

What are you trying to accomplish?

**Comment by E3V3A** [comment]
Getting a poor-mans synth but using a proper keyboard...

**Comment by Gadgetoid** [comment]
This can be done with off the shelf software- but bizarrely, after spending a few hours playing with various synth programs on the Pi (Yoshimi, FluidSynth, etc), I found that writing my own code to accomplish the same effect had much, much better results.

It's not really a synth though, which is a shame, but more a sample-trigger, or sampler at best. I'd really wanted something properly synthy.

If you want to get down to basics and really learn how to read MIDI messages, hook up your keyboard to your Pi and open `/dev/midi` in Python as a binary file and read from it:

https://ccrma.stanford.edu/~craig/articles/linuxmidi/misc/essenmidi.html

I had some code to do this, but unfortunately I wrote it when my laptop was in for repairs on a Pi I don't have access to :(

I believe pygame can handle MIDI input too,  but for some reason I can't load the docs.

**Comment by Gadgetoid** [comment]
I threw together another example today, not quite what you're looking for but it demonstrates handling of MIDI input in a very basic "you should probably never do it this way" fashion: https://gist.github.com/Gadgetoid/7174f8b744e857936e431f7e912e7ca6
