### ISSUE TITLE
No sound in the 8bit-synth.py example

### ISSUE THREAD

**Issue by neauoire** [pimoroni/Piano-HAT#15]
Hi,

On a fresh raspbian install, with the pianoHat, running the `simple-piano.py`/`learn-to-play.py` examples just fine. 

```
8-bit Piano HAT

This advanced example demonstrates software synthesis.

It uses pygame's sndarray.make_sound method to create
8bit tones with specific frequency, bitrate and samplerates.

Instrument = Toggle Sine Wave
Octave ^ = Toggle Saw Wave
Octave V = Toggle Square Wave

Please wait while Pygame is set up and samples are generated...

Press CTRL+C to exit!

Initializing subsystem...
Generating samples...
Now, make beautiful music...
Saw: ON
Square: ON
Sine: OFF
```

Everything checks out, but no output. Anyone else having this issue?

**Comment by Gadgetoid** [comment]
Do you get any sound when you run `speaker-test -c2 -twav`?

**Comment by neauoire** [comment]
I did

**Comment by Gadgetoid** [comment]
Yup, I'm having the same problem! Leave it with me.

**Comment by Gadgetoid** [comment]
Hopefully fixed with: https://github.com/pimoroni/Piano-HAT/commit/b8ee4e89a4419f7e883ee7f32a41455fcef0ed3b

**Comment by neauoire** [comment]
Will give it a try in a day or two :)
Cheers

**Comment by neauoire** [comment]
Sorry, yes. That fixed it for me.
Weird, I was certain I answered this post..

**Comment by neauoire** [comment]
Wait, no.
Still no sound when you pull fresh from: 
```
curl https://get.pimoroni.com/pianohat | bash
```
